version: '3.8'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./site:/usr/share/nginx/html:ro
    expose:
      - "80"
    # Optional for local preview during development:
    # ports:
    #   - "8080:80"
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run mrithang-site
    volumes:
      - ./.cloudflared:/etc/cloudflared:ro
    depends_on:
      - web
    restart: unless-stopped
